FROM golang:1.19-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o ./pokemon-go-pvp ./server/main.go
 
 
FROM alpine:latest AS runner
WORKDIR /app
COPY --from=builder /app/pokemon-go-pvp .
EXPOSE 8080
ENTRYPOINT ["./pokemon-go-pvp"]
